- type: entity
  id: CEBaseWallmount
  abstract: true
  categories: [ ForkFiltered ]
  placement:
    mode: SnapgridCenter
  components:
  - type: Transform
    anchored: true
  - type: Clickable
  - type: InteractionOutline
  - type: Sprite
    drawdepth: Mobs
  - type: CEWallmount
  - type: Physics
    canCollide: false
