- type: entity
  parent: BaseStructure
  id: CEBaseThinWindow
  abstract: true
  categories: [ ForkFiltered ]
  name: thin window
  description: A narrow window that provides visibility while maintaining structure.
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Sprite
    offset: 0, 0.2
    drawdepth: Mobs
    state: fence
  - type: Icon
    state: fence
  - type: MeleeSound
    soundGroups:
      Brute:
        collection: GlassSmack
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Glass
  - type: InteractionPopup
    interactSuccessString: comp-window-knock
    messagePerceivedByOthers: comp-window-knock
    interactSuccessSound:
      path: /Audio/Effects/glass_knock.ogg
  - type: ExaminableDamage
    messages: WindowMessages
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,0.1,0.5,0.3"
        density: 1000
        mask:
        - FullTileMask
        layer:
        - GlassLayer
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: WindowShatter
      - !type:DoActsBehavior
        acts: [ "Destruction" ]

- type: entity
  parent: BaseStructure
  id: CEBaseThinWindowDoor
  abstract: true
  categories: [ ForkFiltered ]
  name: thin window door
  description: Thin window doors. What's your next move?
  components:
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: MeleeSound
    soundGroups:
      Brute:
        collection: GlassSmack
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Glass
  - type: ExaminableDamage
    messages: WindowMessages
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,0.1,0.5,0.3"
        density: 1000
        mask:
        - FullTileMask
        layer:
        - GlassLayer
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: WindowShatter
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Sprite
    offset: 0, 0.2
    drawdepth: Mobs
    layers:
    - state: door_closed
      map: ["enum.DoorVisualLayers.Base"]
  - type: Icon
    state: door_closed
  - type: IconSmooth
    mode: NoSprite
  - type: InteractionOutline
  - type: Appearance
  - type: Door
    openSpriteState: door_opened
    closedSpriteState: door_closed
    canPry: false
    occludes: false
    changeAirtight: false
    bumpOpen: false
    clickOpen: true
    canCrush: false
    closeTimeOne: 0
    closeTimeTwo: 0
    openTimeOne: 0
    openTimeTwo: 0
    closedDrawDepth: Mobs
    openDrawDepth: Mobs
    openingAnimationTime: 0
    closingAnimationTime: 0
    openSound:
      path: /Audio/Effects/door_open.ogg
    closeSound:
      path: /Audio/Effects/door_close.ogg
  - type: CEDoorInteractionPopup
    interactSound:
      collection: CEDoorknob
      params:
        variation: 0.03
        volume: -5
  - type: Lock
    locked: true
  - type: CEDirectionalLatch
