# Default base mob proto

- type: entity
  parent:
  - BaseMob
  - MobCombat
  - CEMobDamageable
  - CEMobStarving
  - MobBloodstream
  - MobFlammable
  - CEMobTemperature
  - MobPolymorphable
  - MobRespirator
  id: CESimpleMobBase
  suffix: AI
  abstract: true
  components:
  - type: NpcFactionMember
    factions:
    - CENeutral
  - type: MeleeWeapon
    angle: 0
    animation: WeaponArcBite
  - type: HTN
    rootTask:
      task: IdleCompound
  - type: Climbing
  - type: NameIdentifier
    group: GenericNumber
  - type: SlowOnDamage
    speedModifierThresholds:
      60: 0.7
      80: 0.5
  - type: StandingState
  - type: StatusEffects
    allowed:
    - SlowedDown
    - Stutter
    - Electrocution
    - TemporaryBlindness
    - Pacified
    - Flashed
    - RadiationProtection
    - Adrenaline
  - type: MovementSpeedModifier
    baseWalkSpeed : 4
    baseSprintSpeed : 4
  - type: Reactive
    groups:
      Flammable: [Touch]
      Extinguish: [Touch]
      Acidic: [Touch, Ingestion]
  - type: Body
    prototype: Animal
